name: aviquest
description: AviQuest â€” Gamified bird identification educational app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  just_audio: ^0.9.40
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0

flutter:
  uses-material-design: true
